### ISSUE TITLE
string doesnt work

### ISSUE THREAD

**Issue by Djidane41771** [tenaciousRas/android-plist-parser#2]
hi,

"string" tag parsing is currently not working.

some functions are missing: like getDate()

and it will be wonderfull if you allow parsing an inputstream instead of string XML

regards

**Comment by tenaciousRas** [comment]
Should be fixed now.  Also added a method for parsing InputStreams.  On master and tagged as v0.92

**Comment by tenaciousRas** [comment]
BTW - Date, String, Integer, etc. all implement the IPListSimpleObject interface.  That means you always use getValue() to get the actual Date value.  If the PList-date is in an array or dict - you will call get(int) or getConfigObject(...) to get at it.  Since those methods return PListObjects, you'll need to cast the results to the simple object you're trying to get the value for.  Take a look at the parser's unit test for more help.

**Comment by tenaciousRas** [comment]
fixed in v0.92

**Comment by Djidane41771** [comment]
hi, thanks a lot
